FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["BudgetAppOnContainers.csproj", "."]
RUN dotnet restore "BudgetAppOnContainers.csproj"
COPY . .
RUN dotnet build "BudgetAppOnContainers.csproj" -c Release -o /app/build

FROM build AS publish 
RUN dotnet publish "BudgetAppOnContainers.csproj" -c Release -o /app/build

FROM nginx:alpine as final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwroot .
COPY nginx.conf /etc/nginx/nginx.conf
